#include "External.hpp"
#include "Private.hpp"
#include "Public.hpp"

#include "MemoryManager.cpp"
#include "Migration.cpp"
#include "Descriptor.cpp"
#include "AbstractObject.cpp"
#include "Variant.cpp"
#include "NativeDescriptors.cpp"
#include "Attribute.cpp"
#include "Method.cpp"
#include "ReflectionManager.cpp"
#include "Stream.cpp"
#include "AbstractSerializer.cpp"
#include "DescriptorExtension.cpp"
#include "AttributeExtension.cpp"
#include "MethodExtension.cpp"
#include "BinaryStream.cpp"
#include "ID.cpp"
#include "StringUtils.cpp"
#include "UnitTest.cpp"
#include "ListConcept.cpp"
#include "StlDescriptors.cpp"
#include "LuaScriptManager.cpp"
#include "LuaScriptManagerUnitTest.cpp"
#include "Object.cpp"
#include "LuaScript.cpp"
#include "enum.cpp"
#include "ImplementationFactory.cpp"
#include "FastDelegateUnitTest.cpp"
#include "SignalSlotUnitTest.cpp"
#include "SignalSlotDescriptors.cpp"

void linkCore(){
}